### PR TITLE
Implement `Format` public interface

### PR DESCRIPTION
**Pull request by MichaelHatherly**
cc: @SimonDanisch, hopefully this iterator interface is sufficient for what you need in `GLVisualize`?

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
From a quick look at https://github.com/JuliaGL/GLVisualize.jl/blob/master/examples/texthighlight.jl it seems that it would all be replaced by something like

```julia
using Highlights, Highlights.Format

immutable BufferWrapper <: IO
    buffer::IOBuffer
    colours::Vector{RGBA{Float32}}
    BufferWrapper() = new(IOBuffer(), RGBA{Float32}[])
end

function Format.render(io::IO, ::MIME"???", tokens::Format.TokenIterator)
    local fg = tokens.theme.base.fg
    local default = fg.active ?
        RGBA{Float32}(fg.r/255, fg.g/255, fg.b/255) :
        RGBA(0f0, 0f0, 0f0, 0f0)
    for (str, id, style) in tokens
        print(io.buffer, str)
        local colour = style.fg.active ?
            RGBA{Float32}(style.fg.r/255, style.fg.g/255, style.fg.b/255) :
            default
        append!(io.colours, fill(colour, length(str)))
    end
end

buffer = BufferWrapper()
highlight(buffer, MIME("???"), source, Lexers.JuliaLexer)
```

Not sure whether that compiles and works correctly since I've not got GLVisualize installed currently.

**Comment by SimonDanisch** [comment]
Thanks a lot, looks promising! :)
Only comment: `Mime("???")` looks a bit confused ... Like, the program doesn't know what it does.
Is this some official convention, or could we easily replace this with something like `MIME("Media/Raw")`/ `MIME("Media/JL")` or so? (JL -> A julia type is the result).

**Comment by MichaelHatherly** [comment]
> Only comment: `Mime("???")` looks a bit confused

That was just a place holder really. In actual use you'd want it to be whatever is most appropriate as the MIME-type for what GLVisualize produces, perhaps `video/gl` or something similar.

**Comment by SimonDanisch** [comment]
Superb :)

**Pull request merged**
