### PR TITLE
Fix LaTeX escaping in text nodes

### PR DESCRIPTION
**Pull request by mortenpi**
This hack might get around the LaTeX escaping problem, fixing #28. @sebastianpech, would you be willing to test this by any chance?

### CODE REVIEW

**Comment by sebastianpech** [comment]
Sure I'll test it. Why did you choose to escape anyway though listings allows those characters? Wouldn't it be simpler to do something like this in `render` (Thats what I tested in my fork)?
```
     if id === :t
            print(io,str)
        else
            print(io, "(*@\\HLJL", id, "{")
            escape(io, mime, str)
            print(io, "}@*)")
        end
```
I checked the chars you escape for latex and 
```
\begin{lstlisting}
` \ $ % # & \ ^ _ {} ~
\end{lstlisting}
```
yields
image

**Comment by mortenpi** [comment]
If you have `\end{lstlisting}` or `(*@` in your code, then it will break it I believe. Although.. `(*@` will break it even with the current approach?

**Comment by sebastianpech** [comment]
I see. Yes `(*@` would break it. I thought about a second thing thats problematic with escaping for latex. Unicode chars are currently not handled at all right? Weave.jl uses a quite clever method for that by iterating over `REPL.REPLCompletions: latex_symbols` and replacing every occurrence of a unicode char with the latex representation. That would be a cool thing to do in Highlights.jl as well.

This would also solve JunoLab/Weave.jl#236

latex_symbols:
```
Dict{String,String} with 2492 entries:
  "\\1/8"                => "⅛"
  "\\bscra"              => "𝓪"
  "\\guilsinglright"     => "›"
  "\\blacktriangleright" => "▶"
  "\\bisansc"            => "𝙘"
  "\\^4"                 => "⁴"
  "\\Re"                 => "ℜ"
  "\\pitchfork"          => "⋔"
  "\\bisanskappa"        => "𝞳"
  "\\bbz"                => "𝕫"
  "\\blockqtrshaded"     => "░"
  "\\urcorner"           => "⌝"
  "\\frakY"              => "𝔜"
  "\\^2"                 => "²"
  "\\pi"                 => "π"
  "\\nless"              => "≮"
  "\\sqsubseteq"         => "⊑"
  "\\Updownarrow"        => "⇕"
  "\\leftarrowbsimilar"  => "⭋"
  "\\bbF"                => "𝔽"
  ⋮                      => ⋮
```

**Comment by sebastianpech** [comment]
This is the function that replaces the unicode characters https://github.com/JunoLab/Weave.jl/blob/e7e5bd7c7fe8f051644a23422f9df17a6b505c00/src/format.jl#L280

**Comment by sebastianpech** [comment]
I tested this today and encountered some serious difficulties with escaping. I wanted to use the babel package with ngerman which activates `"a`, `"s`, ... and so on, but, because of listings escapeinside a string `"something"` is now no more protected by the verbatim and is transformed into `ßomething"`. 

If you think having
- support for unicode characters like in weave.jl (In my opinion highlights.jl is the better place for solving this)
- support for babel
I'm willing to work on that. I'm currently starting a project that relies on that features so that would be a good testing ground.

**Comment by mortenpi** [comment]
Sorry, I should've replied earlier. Yeah, that is a fair point about Unicode and the `REPL.REPLCompletions` approach seems neat. You are more than welcome to supersede this PR with a proper fix -- I am a bit short on time at the moment, so I am not sure when I would actually get around to it myself.

**Comment by sebastianpech** [comment]
Good. Is there a proper way of continuing on this PR besides me creating a new PR and fetching from mp/fix-28?

**Comment by mortenpi** [comment]
I think a new PR is the only option.

**Comment by mortenpi** [comment]
Superseded by #30.

**Pull request closed without merging**
